# Starter pipeline
# Minimal Terraform pipeline

trigger:
- none 

pool:
  name: Cloudinfa2

steps:
- task: TerraformInstaller@1
  displayName: 'Install Terraform'
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  displayName: 'Terraform Init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'cloudinfanew'
    backendAzureRmOverrideSubscriptionID: '5b810eac-4419-4b63-bec3-e76a59097aef'
    backendAzureRmResourceGroupName: 'aks-rg'
    backendAzureRmStorageAccountName: 'aksado1'
    backendAzureRmContainerName: 'aksado1'
    backendAzureRmKey: 'tfstate'

- task: TerraformTask@5
  displayName: 'Terraform Fmt'
  inputs:
    provider: 'azurerm'
    command: 'fmt'

- task: TerraformTask@5
  displayName: 'Terraform Validate'
  inputs:
    provider: 'azurerm'
    command: 'validate'

- task: TerraformTask@5
  displayName: 'Terraform Plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'cloudinfanew'
    environmentAzureRmOverrideSubscriptionID: '5b810eac-4419-4b63-bec3-e76a59097aef'

- task: TerraformTask@5
  displayName: 'Terraform Apply'
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'cloudinfanew'
    environmentAzureRmOverrideSubscriptionID: '5b810eac-4419-4b63-bec3-e76a59097aef'
